sonar.projectKey=pet-clinic
sonar.organization=imssolar

# Paths
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java version
sonar.java.source=11
sonar.java.binaries=build/classes/java/main

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/build/**,**/bin/**,**/*.gradle