name: SonarCloud Workflow

on:
  push:
    branches:
      - main
      
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps: 
      - name: Compilación
        run: |
          echo 'Aqui Compilamos' 

  TESTING:
    runs-on: ubuntu-latest
    steps: 
      - name: Testing
        run: |
          echo 'Aqui se Realizan Pruebas' 

  DEPLOY:
    runs-on: ubuntu-latest
    steps: 
      - name: Testing
        run: |
          echo 'SE DESPLIEGA' 
