name: SonarCloud Workflow

on:
  push:
    branches:
      - main
      
jobs:
  PRUEBA:
    runs-on: ubuntu-latest
    steps: 
      - name: Imprimir Code
        run: |
          echo 'Hola Mundo' 
          