name: SonarCloud Workflow

on:
  push:
    branches:
      - main
      - feature-fabian
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps: 
      - name: Compilación
        run: |
          echo 'Aqui Compilamos' 
          echo 'IMPRIMIMOS'

  TESTING:
    runs-on: ubuntu-latest
    steps: 
      - name: Testing
        run: |
          echo 'Aqui se Realizan Pruebas' 
          echo 'Fallo testing'
          exit 1

  DEPLOY:
    runs-on: ubuntu-latest
    steps: 
      - name: Despliegue
        run: |
          echo 'SE DESPLIEGA' 
